from typing import Dict, List

# key(metaType) -> pk fields (single or composite)
# Update this map as you learn more about each dataset.
PK_FIELDS_BY_KEY: Dict[str, List[str]] = {
    "ActionCost": ["code", "modeType"],
    "Area": ["code"],
    "BattleZoneReward": ["code"],
    "BulletCapacity": ["itemCode"],
    "Character": ["code"],
    "CharacterAttributes": ["characterCode", "mastery"],
    "CharacterExp": ["level"],
    "CharacterLevelUpStat": ["code"],
    "CharacterMastery": ["code"],
    "CharacterModeModifier": ["characterCode", "weaponType"],
    "CharacterSkin": ["code"],
    "Collectible": ["code", "mode"],
    "DropGroup": ["dropType", "groupCode", "itemCode", "mode"],
    "GainExp": ["startTime", "endTime"],
    "GainScore": ["code"],
    "GameTip": ["key"],
    "InfusionProduct": ["code"],
    "ItemArmor": ["code"],
    "ItemConsumable": ["code"],
    "ItemMisc": ["code"],
    "ItemSearchOptionV2": ["code"],
    "ItemSpawn": ["code", "itemCode"],
    "ItemSpecial": ["code"],
    "ItemWeapon": ["code"],
    "Level": ["level"],
    "LoadingTip": ["code"],
    "MasteryExp": ["code", "conditionType"],
    "MasteryLevel": ["code"],
    "MasteryStat": ["code", "characterCode"],
    "Monster": ["code", "mode"],
    "MonsterDropGroup": ["monsterCode", "monsterLevel"],
    "MonsterLevelUpStat": ["code", "mode"],
    "MonsterSpawnLevel": ["code"],
    "NaviCollectAndHunt": ["code"],
    "NearByArea": ["code"],
    "RandomEquipment": ["code"],
    "RecommendedList": ["code"],
    "Season": ["seasonID"],
    "SummonObjectStat": ["code"],
    "TacticalSkillSet": ["code"],
    "TacticalSkillSetGroup": ["group"],
    "Trait": ["code"],
    "VFCredit": ["code"],
    "WeaponTypeInfo": ["type"],
}
